name: 'build and deploy docker'

on:
  push:
    tags:
        - '*'

jobs:
    release-docker-image-job:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
    
        - name: Build image and push to github packages (Docker registry)   
          uses: mr-smithers-excellent/docker-build-push@v6
          with:
            image: ${{ github.event.repository.name }}
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}