name: 'build and deploy'

on:
  push:
    tags:
        - 'v1000'

jobs:
  build-prod-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up nodejs version to 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: run ci
        run: npm ci

      - name: Run build production (create Dist folder)
        run: npm run build

      - name: List directory
        run: ls

      - name: Upload dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist-production
          path: dist

  deploy-to-production:
    needs: build-prod-job
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: Download dist folder artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-production
          path: dist
        
      - run: ls
      - run: ls dist
      # deploy to cloud
      - uses: actions/checkout@v4

      - name: publish to github page
        uses: Serhiika/VuePagesAction@1.0.4
        with: 
          username: ${{ github.actor }} # pigman8857
          reponame: ${{ github.event.repository.name }} # vue-github-app
          token: ${{ secrets.GITHUB_TOKEN }}
    