name: 'build and deploy'

on:
  push:
    tags:
        - '*'

jobs:
  build-prod-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up nodejs version to 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: run ci
        run: npm ci

      - name: Run build production (create Dist folder)
        run: npm run build

      - name: Upload dist folder
        uses: actions/upload-artifact@v3
        with:
          name: dist-production
          path: dist