name: my first CI

on: 
    push:
        branches: 
            - main
    pull_request: 
        branches: 
            - 'main'

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello"
