name: my first CI

on: 
    push:
        branches: 
            - main
    pull_request: 
        branches: 
            - 'main'

jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello"
            - uses: actions/checkout@v3

            - name: Set up nodejs version to 18.x
              uses: actions/setup-node@v3
              with:
                node-version: '18'

            - name: install Dependencies
              run: npm i

            - name: Run eslint
              run: npm run lint

            - name: Run format code with prettier
              run: npm run format
              
            - name: Run unit test
              run: npm run test:unit
        

